### ISSUE TITLE
OSX: App is damaged 

### ISSUE THREAD

**Issue by Naesstrom** [thorrak/brewflasher#1]
Tried to run this today on my mac but got the following error message instead:
![Screenshot 2020-02-05 at 14 13 12](https://user-images.githubusercontent.com/6575206/73844912-d00f3680-4821-11ea-8dc9-31a8d0ad4f81.png)

Tried control-click and open it if it was some security problem but still the same problem.

**Comment by thorrak** [comment]
Which version of MacOS are you using?

**Comment by Naesstrom** [comment]
Catalina _(10.15.3 (19D76))_

**Comment by thorrak** [comment]
[rant] Google says it's due to Gatekeeper. Of _course_ it would be gatekeeper. I spent hours working on getting my code signing IDs set up so Gatekeeper wouldn't be an issue, tested on two separate macs, and yet - here we are. The sad thing is that the main reason this is so difficult to solve is because Apple refuses to acknowledge that there are ways to build apps other than in Xcode, and thus all of the documentation dates WAY back (~8 years in some cases) and is contradictory at best. [/rant]

Anyways.

I've got an idea as to a way that I might be able to fix this (by converting to a DMG, zipping that, and then uploading that instead) - I'll give that a try tonight and see if that resolves the issue. If it doesn't, I'll go back to Apple and see if I can get them to explain where the disconnect is.

**Comment by thorrak** [comment]
As a quick update, I think I have a lead on the proper way to get everything signed and Gatekeeper ready - I’m working through that now. 

Added benefit - the re-release of the (hopefully signed!) BrewFlasher will now be Retina-capable ;)

**Comment by lbussy** [comment]
> BrewFlasher will now be Retina-capable ;)

At least you're working on important things. :)

**Comment by thorrak** [comment]
@Naesstrom - I just updated the release with the new, re-signed version of BrewFlasher. Please let me know if this works or if you have any issues.

**Comment by Naesstrom** [comment]
Yey, seems to work now!
Where does it get versions of iSpindel btw, latest release is 6.2.0 on the universam repo but the app shows 5.6.1
![image](https://user-images.githubusercontent.com/6575206/74134095-38776280-4bea-11ea-8736-48a348ae0f60.png)

**Comment by thorrak** [comment]
Perfect! That’s what I was hoping to hear. :)

I feel _somewhat_ validated - this issue is apparently relatively new for apps packaged with PyInstaller as they only just begun debating it this past weekend. I still haven’t fully determined how to get it to “sandbox” properly such that it could be submitted to the Mac App Store, but so long as it can be distributed at all I’m a happy camper.  


The firmware list is shared with Fermentrack and is based on a list that I manually maintain. For firmware that either I or people I directly collaborate with maintain, you can generally expect the links to remain up to date — this includes BrewBubbles, BrewPi-ESP8266, TiltBridge, etc. For other projects, it may take some gentle nudging to get it updated. At some point I may build a script that watches the GitHub releases for a specific repo in order to track updates, but that’s not a project I’m prioritizing just yet. For now, it’s probably going to take people poking me via issues here if I don’t catch that it’s updated. 

That said, 6.2.0 should now be available. ;)
