### ISSUE TITLE
Pull GitHub Info for Project

### ISSUE THREAD

**Issue by lbussy** [thorrak/brewflasher#10]
Using GitHub as a code repository seems ubiquitous, most errors seem to come from the firmware links being incorrect.

Allow adding the GitHub link to the project in order that firmware selection can be a true selection rather than a cut and paste.

Extra credit:  Poll (hourly?) and if chosen in the project setup, grab the latest release firmware automatically.

**Comment by thorrak** [comment]
Fundamentally, the issue is that the Fermentrack firmware tracker wasn't intended to be particularly user friendly as it didn't track too many different projects. There's a couple of different options for making it more user-friendly - GitHub integration being one of them.

If we get to the point where it starts to become unwieldy (ie - if other authors want to add additional projects added to BrewFlasher) then I'll build out the update workflow. Until then, it's going to remain a bit of a beast for the handful of people that use it, most likely.

**Comment by thorrak** [comment]
Behind the scenes, I now have GitHub webhook support which allows for automated project updates so long as the author of the project sets it up and supports it. Not quite polling, but still automated!
