### ISSUE TITLE
LittleFS Not Supported

### ISSUE THREAD

**Issue by lbussy** [thorrak/brewflasher#5]
SPIFFS is now [deprecated for ESP8266](https://arduino-esp8266.readthedocs.io/en/latest/filesystem.html#spiffs-deprecation-warning).  LittleFS is more or less a drop-in for SPIFFS, however, Brewflasher will not upload the LittleFS file.  It looks like it never tries actually:

```
Downloading firmware...
Downloaded successfully!

Command: esptool.py --chip esp8266 write_flash --flash_mode dio 0x00000 C:\Users\Xxxxxxxx\AppData\Local\Temp\firmware.bin

esptool.py v2.8
Found 1 serial ports
Serial port COM6
Connecting....
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: 84:f3:eb:e3:fd:f0
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 4MB
Compressed 506880 bytes to 348030...
Wrote 506880 bytes (348030 compressed) at 0x00000000 in 30.4 seconds (effective 133.4 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...

Firmware successfully flashed. Unplug/replug or reset device to switch back to normal boot mode.
```

On the Firmware admin tool, the LittleFS link is present and valid, however, no checksum was created.

**Comment by thorrak** [comment]
I think there are two issues here, actually, though neither prevents flashing LittleFS data:

1. The error message BrewFlasher presents when a file fails the checksum test is not descriptive. Download errors should be more verbose as to what exactly failed (and what should be done about it)
2. The firmware models refer to the filesystem bin as "spiffs", rename downloads to that, etc. Nothing wrong with that (it should be hidden from the user) but this can be confusing to programmers. The firmware models (and BrewFlasher handler) should instead refer to the spiffs items as "filesystem" rather than "spiffs"

I'll get issues opened for these.

**Comment by thorrak** [comment]
Opened #6 and #7 for these issues. Closing this.
